title: DSC80 Final Project
description: We chose this dataset because firstly it is a comprehensive dataset to perform hypothesis testing and make both regression and classification predictions (due to its 57 columns), and also the fact the realism of the data and impact of it's predictions.
theme: minima